server:
  port: 8181
    #8181
spring:
  application:
    name: vehicle-reservation
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    password: ${PGPASSWORD}
    username: ${PGUSER}
  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day


#      username: user_reservations_vehicle
#      password: admin1234